/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.hr.saas.app.kafka.model.avro;
@org.apache.avro.specific.AvroGenerated
public enum DepartmentEmployeeStatus implements org.apache.avro.generic.GenericEnumSymbol<DepartmentEmployeeStatus> {
  OK  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"DepartmentEmployeeStatus\",\"namespace\":\"com.hr.saas.app.kafka.model.avro\",\"symbols\":[\"OK\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
