/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.hr.saas.app.kafka.model.avro;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class DepartmentApprovalRequestAvroModel extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -6918869953127209190L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"DepartmentApprovalRequestAvroModel\",\"namespace\":\"com.hr.saas.app.kafka.model.avro\",\"fields\":[{\"name\":\"id\",\"type\":{\"type\":\"string\",\"logicalType\":\"uuid\"}},{\"name\":\"sagaId\",\"type\":{\"type\":\"string\",\"logicalType\":\"uuid\"}},{\"name\":\"departmentId\",\"type\":{\"type\":\"string\",\"logicalType\":\"uuid\"}},{\"name\":\"employeeId\",\"type\":{\"type\":\"string\",\"logicalType\":\"uuid\"}},{\"name\":\"departmentEmployeeStatus\",\"type\":{\"type\":\"enum\",\"name\":\"DepartmentEmployeeStatus\",\"symbols\":[\"OK\"]}},{\"name\":\"createdAt\",\"type\":{\"type\":\"long\",\"logicalType\":\"timestamp-millis\"}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();
  static {
    MODEL$.addLogicalTypeConversion(new org.apache.avro.Conversions.UUIDConversion());
    MODEL$.addLogicalTypeConversion(new org.apache.avro.data.TimeConversions.TimestampMillisConversion());
  }

  private static final BinaryMessageEncoder<DepartmentApprovalRequestAvroModel> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<DepartmentApprovalRequestAvroModel> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<DepartmentApprovalRequestAvroModel> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<DepartmentApprovalRequestAvroModel> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<DepartmentApprovalRequestAvroModel> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this DepartmentApprovalRequestAvroModel to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a DepartmentApprovalRequestAvroModel from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a DepartmentApprovalRequestAvroModel instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static DepartmentApprovalRequestAvroModel fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.util.UUID id;
  private java.util.UUID sagaId;
  private java.util.UUID departmentId;
  private java.util.UUID employeeId;
  private com.hr.saas.app.kafka.model.avro.DepartmentEmployeeStatus departmentEmployeeStatus;
  private java.time.Instant createdAt;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public DepartmentApprovalRequestAvroModel() {}

  /**
   * All-args constructor.
   * @param id The new value for id
   * @param sagaId The new value for sagaId
   * @param departmentId The new value for departmentId
   * @param employeeId The new value for employeeId
   * @param departmentEmployeeStatus The new value for departmentEmployeeStatus
   * @param createdAt The new value for createdAt
   */
  public DepartmentApprovalRequestAvroModel(java.util.UUID id, java.util.UUID sagaId, java.util.UUID departmentId, java.util.UUID employeeId, com.hr.saas.app.kafka.model.avro.DepartmentEmployeeStatus departmentEmployeeStatus, java.time.Instant createdAt) {
    this.id = id;
    this.sagaId = sagaId;
    this.departmentId = departmentId;
    this.employeeId = employeeId;
    this.departmentEmployeeStatus = departmentEmployeeStatus;
    this.createdAt = createdAt.truncatedTo(java.time.temporal.ChronoUnit.MILLIS);
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return id;
    case 1: return sagaId;
    case 2: return departmentId;
    case 3: return employeeId;
    case 4: return departmentEmployeeStatus;
    case 5: return createdAt;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  private static final org.apache.avro.Conversion<?>[] conversions =
      new org.apache.avro.Conversion<?>[] {
      new org.apache.avro.Conversions.UUIDConversion(),
      new org.apache.avro.Conversions.UUIDConversion(),
      new org.apache.avro.Conversions.UUIDConversion(),
      new org.apache.avro.Conversions.UUIDConversion(),
      null,
      new org.apache.avro.data.TimeConversions.TimestampMillisConversion(),
      null
  };

  @Override
  public org.apache.avro.Conversion<?> getConversion(int field) {
    return conversions[field];
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: id = (java.util.UUID)value$; break;
    case 1: sagaId = (java.util.UUID)value$; break;
    case 2: departmentId = (java.util.UUID)value$; break;
    case 3: employeeId = (java.util.UUID)value$; break;
    case 4: departmentEmployeeStatus = (com.hr.saas.app.kafka.model.avro.DepartmentEmployeeStatus)value$; break;
    case 5: createdAt = (java.time.Instant)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'id' field.
   * @return The value of the 'id' field.
   */
  public java.util.UUID getId() {
    return id;
  }


  /**
   * Sets the value of the 'id' field.
   * @param value the value to set.
   */
  public void setId(java.util.UUID value) {
    this.id = value;
  }

  /**
   * Gets the value of the 'sagaId' field.
   * @return The value of the 'sagaId' field.
   */
  public java.util.UUID getSagaId() {
    return sagaId;
  }


  /**
   * Sets the value of the 'sagaId' field.
   * @param value the value to set.
   */
  public void setSagaId(java.util.UUID value) {
    this.sagaId = value;
  }

  /**
   * Gets the value of the 'departmentId' field.
   * @return The value of the 'departmentId' field.
   */
  public java.util.UUID getDepartmentId() {
    return departmentId;
  }


  /**
   * Sets the value of the 'departmentId' field.
   * @param value the value to set.
   */
  public void setDepartmentId(java.util.UUID value) {
    this.departmentId = value;
  }

  /**
   * Gets the value of the 'employeeId' field.
   * @return The value of the 'employeeId' field.
   */
  public java.util.UUID getEmployeeId() {
    return employeeId;
  }


  /**
   * Sets the value of the 'employeeId' field.
   * @param value the value to set.
   */
  public void setEmployeeId(java.util.UUID value) {
    this.employeeId = value;
  }

  /**
   * Gets the value of the 'departmentEmployeeStatus' field.
   * @return The value of the 'departmentEmployeeStatus' field.
   */
  public com.hr.saas.app.kafka.model.avro.DepartmentEmployeeStatus getDepartmentEmployeeStatus() {
    return departmentEmployeeStatus;
  }


  /**
   * Sets the value of the 'departmentEmployeeStatus' field.
   * @param value the value to set.
   */
  public void setDepartmentEmployeeStatus(com.hr.saas.app.kafka.model.avro.DepartmentEmployeeStatus value) {
    this.departmentEmployeeStatus = value;
  }

  /**
   * Gets the value of the 'createdAt' field.
   * @return The value of the 'createdAt' field.
   */
  public java.time.Instant getCreatedAt() {
    return createdAt;
  }


  /**
   * Sets the value of the 'createdAt' field.
   * @param value the value to set.
   */
  public void setCreatedAt(java.time.Instant value) {
    this.createdAt = value.truncatedTo(java.time.temporal.ChronoUnit.MILLIS);
  }

  /**
   * Creates a new DepartmentApprovalRequestAvroModel RecordBuilder.
   * @return A new DepartmentApprovalRequestAvroModel RecordBuilder
   */
  public static com.hr.saas.app.kafka.model.avro.DepartmentApprovalRequestAvroModel.Builder newBuilder() {
    return new com.hr.saas.app.kafka.model.avro.DepartmentApprovalRequestAvroModel.Builder();
  }

  /**
   * Creates a new DepartmentApprovalRequestAvroModel RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new DepartmentApprovalRequestAvroModel RecordBuilder
   */
  public static com.hr.saas.app.kafka.model.avro.DepartmentApprovalRequestAvroModel.Builder newBuilder(com.hr.saas.app.kafka.model.avro.DepartmentApprovalRequestAvroModel.Builder other) {
    if (other == null) {
      return new com.hr.saas.app.kafka.model.avro.DepartmentApprovalRequestAvroModel.Builder();
    } else {
      return new com.hr.saas.app.kafka.model.avro.DepartmentApprovalRequestAvroModel.Builder(other);
    }
  }

  /**
   * Creates a new DepartmentApprovalRequestAvroModel RecordBuilder by copying an existing DepartmentApprovalRequestAvroModel instance.
   * @param other The existing instance to copy.
   * @return A new DepartmentApprovalRequestAvroModel RecordBuilder
   */
  public static com.hr.saas.app.kafka.model.avro.DepartmentApprovalRequestAvroModel.Builder newBuilder(com.hr.saas.app.kafka.model.avro.DepartmentApprovalRequestAvroModel other) {
    if (other == null) {
      return new com.hr.saas.app.kafka.model.avro.DepartmentApprovalRequestAvroModel.Builder();
    } else {
      return new com.hr.saas.app.kafka.model.avro.DepartmentApprovalRequestAvroModel.Builder(other);
    }
  }

  /**
   * RecordBuilder for DepartmentApprovalRequestAvroModel instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<DepartmentApprovalRequestAvroModel>
    implements org.apache.avro.data.RecordBuilder<DepartmentApprovalRequestAvroModel> {

    private java.util.UUID id;
    private java.util.UUID sagaId;
    private java.util.UUID departmentId;
    private java.util.UUID employeeId;
    private com.hr.saas.app.kafka.model.avro.DepartmentEmployeeStatus departmentEmployeeStatus;
    private java.time.Instant createdAt;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.hr.saas.app.kafka.model.avro.DepartmentApprovalRequestAvroModel.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.sagaId)) {
        this.sagaId = data().deepCopy(fields()[1].schema(), other.sagaId);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.departmentId)) {
        this.departmentId = data().deepCopy(fields()[2].schema(), other.departmentId);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.employeeId)) {
        this.employeeId = data().deepCopy(fields()[3].schema(), other.employeeId);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.departmentEmployeeStatus)) {
        this.departmentEmployeeStatus = data().deepCopy(fields()[4].schema(), other.departmentEmployeeStatus);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
      if (isValidValue(fields()[5], other.createdAt)) {
        this.createdAt = data().deepCopy(fields()[5].schema(), other.createdAt);
        fieldSetFlags()[5] = other.fieldSetFlags()[5];
      }
    }

    /**
     * Creates a Builder by copying an existing DepartmentApprovalRequestAvroModel instance
     * @param other The existing instance to copy.
     */
    private Builder(com.hr.saas.app.kafka.model.avro.DepartmentApprovalRequestAvroModel other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.sagaId)) {
        this.sagaId = data().deepCopy(fields()[1].schema(), other.sagaId);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.departmentId)) {
        this.departmentId = data().deepCopy(fields()[2].schema(), other.departmentId);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.employeeId)) {
        this.employeeId = data().deepCopy(fields()[3].schema(), other.employeeId);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.departmentEmployeeStatus)) {
        this.departmentEmployeeStatus = data().deepCopy(fields()[4].schema(), other.departmentEmployeeStatus);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.createdAt)) {
        this.createdAt = data().deepCopy(fields()[5].schema(), other.createdAt);
        fieldSetFlags()[5] = true;
      }
    }

    /**
      * Gets the value of the 'id' field.
      * @return The value.
      */
    public java.util.UUID getId() {
      return id;
    }


    /**
      * Sets the value of the 'id' field.
      * @param value The value of 'id'.
      * @return This builder.
      */
    public com.hr.saas.app.kafka.model.avro.DepartmentApprovalRequestAvroModel.Builder setId(java.util.UUID value) {
      validate(fields()[0], value);
      this.id = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'id' field has been set.
      * @return True if the 'id' field has been set, false otherwise.
      */
    public boolean hasId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'id' field.
      * @return This builder.
      */
    public com.hr.saas.app.kafka.model.avro.DepartmentApprovalRequestAvroModel.Builder clearId() {
      id = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'sagaId' field.
      * @return The value.
      */
    public java.util.UUID getSagaId() {
      return sagaId;
    }


    /**
      * Sets the value of the 'sagaId' field.
      * @param value The value of 'sagaId'.
      * @return This builder.
      */
    public com.hr.saas.app.kafka.model.avro.DepartmentApprovalRequestAvroModel.Builder setSagaId(java.util.UUID value) {
      validate(fields()[1], value);
      this.sagaId = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'sagaId' field has been set.
      * @return True if the 'sagaId' field has been set, false otherwise.
      */
    public boolean hasSagaId() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'sagaId' field.
      * @return This builder.
      */
    public com.hr.saas.app.kafka.model.avro.DepartmentApprovalRequestAvroModel.Builder clearSagaId() {
      sagaId = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'departmentId' field.
      * @return The value.
      */
    public java.util.UUID getDepartmentId() {
      return departmentId;
    }


    /**
      * Sets the value of the 'departmentId' field.
      * @param value The value of 'departmentId'.
      * @return This builder.
      */
    public com.hr.saas.app.kafka.model.avro.DepartmentApprovalRequestAvroModel.Builder setDepartmentId(java.util.UUID value) {
      validate(fields()[2], value);
      this.departmentId = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'departmentId' field has been set.
      * @return True if the 'departmentId' field has been set, false otherwise.
      */
    public boolean hasDepartmentId() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'departmentId' field.
      * @return This builder.
      */
    public com.hr.saas.app.kafka.model.avro.DepartmentApprovalRequestAvroModel.Builder clearDepartmentId() {
      departmentId = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'employeeId' field.
      * @return The value.
      */
    public java.util.UUID getEmployeeId() {
      return employeeId;
    }


    /**
      * Sets the value of the 'employeeId' field.
      * @param value The value of 'employeeId'.
      * @return This builder.
      */
    public com.hr.saas.app.kafka.model.avro.DepartmentApprovalRequestAvroModel.Builder setEmployeeId(java.util.UUID value) {
      validate(fields()[3], value);
      this.employeeId = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'employeeId' field has been set.
      * @return True if the 'employeeId' field has been set, false otherwise.
      */
    public boolean hasEmployeeId() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'employeeId' field.
      * @return This builder.
      */
    public com.hr.saas.app.kafka.model.avro.DepartmentApprovalRequestAvroModel.Builder clearEmployeeId() {
      employeeId = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'departmentEmployeeStatus' field.
      * @return The value.
      */
    public com.hr.saas.app.kafka.model.avro.DepartmentEmployeeStatus getDepartmentEmployeeStatus() {
      return departmentEmployeeStatus;
    }


    /**
      * Sets the value of the 'departmentEmployeeStatus' field.
      * @param value The value of 'departmentEmployeeStatus'.
      * @return This builder.
      */
    public com.hr.saas.app.kafka.model.avro.DepartmentApprovalRequestAvroModel.Builder setDepartmentEmployeeStatus(com.hr.saas.app.kafka.model.avro.DepartmentEmployeeStatus value) {
      validate(fields()[4], value);
      this.departmentEmployeeStatus = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'departmentEmployeeStatus' field has been set.
      * @return True if the 'departmentEmployeeStatus' field has been set, false otherwise.
      */
    public boolean hasDepartmentEmployeeStatus() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'departmentEmployeeStatus' field.
      * @return This builder.
      */
    public com.hr.saas.app.kafka.model.avro.DepartmentApprovalRequestAvroModel.Builder clearDepartmentEmployeeStatus() {
      departmentEmployeeStatus = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'createdAt' field.
      * @return The value.
      */
    public java.time.Instant getCreatedAt() {
      return createdAt;
    }


    /**
      * Sets the value of the 'createdAt' field.
      * @param value The value of 'createdAt'.
      * @return This builder.
      */
    public com.hr.saas.app.kafka.model.avro.DepartmentApprovalRequestAvroModel.Builder setCreatedAt(java.time.Instant value) {
      validate(fields()[5], value);
      this.createdAt = value.truncatedTo(java.time.temporal.ChronoUnit.MILLIS);
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'createdAt' field has been set.
      * @return True if the 'createdAt' field has been set, false otherwise.
      */
    public boolean hasCreatedAt() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'createdAt' field.
      * @return This builder.
      */
    public com.hr.saas.app.kafka.model.avro.DepartmentApprovalRequestAvroModel.Builder clearCreatedAt() {
      fieldSetFlags()[5] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public DepartmentApprovalRequestAvroModel build() {
      try {
        DepartmentApprovalRequestAvroModel record = new DepartmentApprovalRequestAvroModel();
        record.id = fieldSetFlags()[0] ? this.id : (java.util.UUID) defaultValue(fields()[0]);
        record.sagaId = fieldSetFlags()[1] ? this.sagaId : (java.util.UUID) defaultValue(fields()[1]);
        record.departmentId = fieldSetFlags()[2] ? this.departmentId : (java.util.UUID) defaultValue(fields()[2]);
        record.employeeId = fieldSetFlags()[3] ? this.employeeId : (java.util.UUID) defaultValue(fields()[3]);
        record.departmentEmployeeStatus = fieldSetFlags()[4] ? this.departmentEmployeeStatus : (com.hr.saas.app.kafka.model.avro.DepartmentEmployeeStatus) defaultValue(fields()[4]);
        record.createdAt = fieldSetFlags()[5] ? this.createdAt : (java.time.Instant) defaultValue(fields()[5]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<DepartmentApprovalRequestAvroModel>
    WRITER$ = (org.apache.avro.io.DatumWriter<DepartmentApprovalRequestAvroModel>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<DepartmentApprovalRequestAvroModel>
    READER$ = (org.apache.avro.io.DatumReader<DepartmentApprovalRequestAvroModel>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}










